# Autogenerated by devscripts/update-version.py

__version__ = '2024.01.23.192803'

RELEASE_GIT_HEAD = '434c12434bdb11033ba8cd562e94c2f13917947e'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'

ORIGIN = 'local'

_pkg_version = '2024.01.23.192803'
