name: UpdateVersion
on:
  push:
    branches:
      - 'main'

permissions:
  contents: write

jobs:
  prepare:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Get Git Version
        uses: docker://gittools/gitversion:5.8.2-ubuntu.20.04-6.0-amd64
        with:
          args: /github/workspace -nofetch -output json -overrideconfig assembly-versioning-format="{Major}.{Minor}.{Patch}.{env:BUILD_NUMBER ?? 0}"
          # args: /github/workspace -exec -nofetch "-c \"echo $GitVersion_MajorMinorPatch > /github/workspace/version.txt\""
