name: UpdateVersion
on:
  push:
    branches:
      - 'main'

permissions:
  contents: write
  
jobs:
  job1:
    name: Modifiy repository files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Modifiy the specific files using scripts
        run: |
          python ./.github/workflows/update_version.py
      - name: Commit and push changes
        run: |
          git config --global user.name "FabioMassaretto"
          git config --global user.email "fmassaretto@outlook.com"
          git add -A
          git commit -m "Automatic version updated"
          git push
